version: 2


deploy:
  dockerhub:
    branch: master
    commands: 
      - $DOCKER_HUB_TRIGGER

jobs:
  build:
    working_directory: /temp
    docker:
#      - image: microsoft/aspnetcore:2.0
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build

